=begin
#Brevo API

#Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 

OpenAPI spec version: 3.0.0
Contact: contact@brevo.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.19

=end

require 'date'

module Brevo
  class GetWhatsAppConfig
    # Id of the WhatsApp business account
    attr_accessor :whatsapp_business_account_id

    # Sending limit Information of the WhatsApp API account
    attr_accessor :sending_limit

    # Quality status of phone number associated with WhatsApp account. There are three quality ratings. example - **High (GREEN) , Medium (YELLOW) and Low(RED)**
    attr_accessor :phone_number_quality

    # Status information related to WhatsApp Api account
    attr_accessor :whatsapp_business_account_status

    # Verification status information of the Business account
    attr_accessor :business_status

    # Status of the name associated with WhatsApp Phone number
    attr_accessor :phone_number_name_status

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'whatsapp_business_account_id' => :'whatsappBusinessAccountId',
        :'sending_limit' => :'sendingLimit',
        :'phone_number_quality' => :'phoneNumberQuality',
        :'whatsapp_business_account_status' => :'whatsappBusinessAccountStatus',
        :'business_status' => :'businessStatus',
        :'phone_number_name_status' => :'phoneNumberNameStatus'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'whatsapp_business_account_id' => :'String',
        :'sending_limit' => :'String',
        :'phone_number_quality' => :'String',
        :'whatsapp_business_account_status' => :'String',
        :'business_status' => :'String',
        :'phone_number_name_status' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'whatsappBusinessAccountId')
        self.whatsapp_business_account_id = attributes[:'whatsappBusinessAccountId']
      end

      if attributes.has_key?(:'sendingLimit')
        self.sending_limit = attributes[:'sendingLimit']
      end

      if attributes.has_key?(:'phoneNumberQuality')
        self.phone_number_quality = attributes[:'phoneNumberQuality']
      end

      if attributes.has_key?(:'whatsappBusinessAccountStatus')
        self.whatsapp_business_account_status = attributes[:'whatsappBusinessAccountStatus']
      end

      if attributes.has_key?(:'businessStatus')
        self.business_status = attributes[:'businessStatus']
      end

      if attributes.has_key?(:'phoneNumberNameStatus')
        self.phone_number_name_status = attributes[:'phoneNumberNameStatus']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      phone_number_quality_validator = EnumAttributeValidator.new('String', ['GREEN', 'YELLOW', 'RED'])
      return false unless phone_number_quality_validator.valid?(@phone_number_quality)
      phone_number_name_status_validator = EnumAttributeValidator.new('String', ['APPROVED', 'PENDING', 'REJECTED'])
      return false unless phone_number_name_status_validator.valid?(@phone_number_name_status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_quality Object to be assigned
    def phone_number_quality=(phone_number_quality)
      validator = EnumAttributeValidator.new('String', ['GREEN', 'YELLOW', 'RED'])
      unless validator.valid?(phone_number_quality)
        fail ArgumentError, 'invalid value for "phone_number_quality", must be one of #{validator.allowable_values}.'
      end
      @phone_number_quality = phone_number_quality
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] phone_number_name_status Object to be assigned
    def phone_number_name_status=(phone_number_name_status)
      validator = EnumAttributeValidator.new('String', ['APPROVED', 'PENDING', 'REJECTED'])
      unless validator.valid?(phone_number_name_status)
        fail ArgumentError, 'invalid value for "phone_number_name_status", must be one of #{validator.allowable_values}.'
      end
      @phone_number_name_status = phone_number_name_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          whatsapp_business_account_id == o.whatsapp_business_account_id &&
          sending_limit == o.sending_limit &&
          phone_number_quality == o.phone_number_quality &&
          whatsapp_business_account_status == o.whatsapp_business_account_status &&
          business_status == o.business_status &&
          phone_number_name_status == o.phone_number_name_status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [whatsapp_business_account_id, sending_limit, phone_number_quality, whatsapp_business_account_status, business_status, phone_number_name_status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Brevo.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
